#Specify the sever port
server:
  port:
   9099

# Custom Logging message
logging:
  level:
    org:
      springframework: info
    com:
      bankingManagement: debug
  file:
    name: spring_app_log_file.log
  pattern:
    name: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# MySQL database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# Actuator endpoints config
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env
  endpoint:
    health:
      show-details: always



